import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
# TERM = "xterm-256color"   # naive workaround for missing terminfo;

[window]
resize_increments = true
option_as_alt = "OnlyLeft"  # for macOS;

[window.dimensions]
columns = 80
lines = 24

[font]
size = 16.0

[font.normal]
family = "MesloLGS Nerd Font"
