# Colors (Gruvbox light hard)

# Default colors
[colors.primary]
# hard contrast background = = '#f9f5d7'
background = '#f9f5d7'
# soft contrast background = = '#f2e5bc'
foreground = '#3c3836'

# Normal colors
[colors.normal]
black   = '#f9f5d7'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#7c6f64'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#9d0006'
green   = '#79740e'
yellow  = '#b57614'
blue    = '#076678'
magenta = '#8f3f71'
cyan    = '#427b58'
white   = '#282828'


## XTerm's default colors
#
## Default colors
#[colors.primary]
#background = '#000000'
#foreground = '#ffffff'
#
## Normal colors
#[colors.normal]
#black   = '#000000'
#red     = '#cd0000'
#green   = '#00cd00'
#yellow  = '#cdcd00'
#blue    = '#0000ee'
#magenta = '#cd00cd'
#cyan    = '#00cdcd'
#white   = '#e5e5e5'
#
## Bright colors
#[colors.bright]
#black   = '#7f7f7f'
#red     = '#ff0000'
#green   = '#00ff00'
#yellow  = '#ffff00'
#blue    = '#5c5cff'
#magenta = '#ff00ff'
#cyan    = '#00ffff'
#white   = '#ffffff'

[env]
# TERM = "xterm-256color"   # naive workaround for missing terminfo;

[window]
resize_increments = true
option_as_alt = "OnlyLeft"  # for macOS;

[window.dimensions]
columns = 80
lines = 25

[font]
size = 14.0

[font.normal]
family = "MesloLGMDZ Nerd Font"
#family = "UbuntuMono Nerd Font"
