set guioptions=egm
set guifont=Meslo\ LG\ M\ DZ:h14
set guifontwide=Noto\ Sans\ CJK\ KR:h15,Symbols\ Nerd\ Font\ Mono

set columns=80
set lines=25

" Disable cursor blinking 
set guicursor+=a:blinkon0
