# History
HISTFILE=~/.zsh_history
HISTSIZE=20000
SAVEHIST=20000
setopt HIST_IGNORE_DUPS

export VISUAL=vim
export EDITOR=vim
export PAGER=less

# Completion
zstyle ':completion:*' completer _expand _complete _approximate
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' menu select
zstyle :compinstall filename '~/.zshrc'
zstyle ':completion:*:functions' ignored-patterns '_*'

autoload -Uz compinit
compinit

bindkey -e

# Prompt
cUSR="%F{cyan}%B"
cPWD="%F{magenta}%B"
cSTD="%b%f"
PROMPT="%m ${cUSR}%n${cSTD} ${cPWD}%~${cSTD}
%# "
unset cUSR cPWD cSTD

if command -v fzf >/dev/null 2>&1; then
  # Set up fzf key bindings and fuzzy completion
  source <(fzf --zsh)
else
  # Use CTRL-S for i-search
  stty -ixon
fi
